#!/bin/bash

answer=0
lattice="tri"
tempz=0.01
tempk=0.001
tempi=-0.00003
#tempi=$(awk "BEGIN {print (${tempk}-${tempz})/32}")
intname="barr_1"
jay=-0.800737
lc=1
c=(1)
radij=24
mrad=1
ls=4.5
le=1
side1=84
side2=78
frac=0.0949328
#frac=($(awk "BEGIN {print 1/2}") $(awk "BEGIN {print 1/3}") $(awk "BEGIN {print 1/4}") $(awk "BEGIN {print 1/5}") $(awk "BEGIN {print 1/6}") $(awk "BEGIN {print 1/7}") $(awk "BEGIN {print 1/8}") $(awk "BEGIN {print 1/9}") $(awk "BEGIN {print 1/10}") $(awk "BEGIN {print 1/11}") $(awk "BEGIN {print 1/12}") $(awk "BEGIN {print 1/13}") $(awk "BEGIN {print 1/14}") $(awk "BEGIN {print 1/15}") $(awk "BEGIN {print 1/16}") $(awk "BEGIN {print 1/17}") $(awk "BEGIN {print 1/18}") $(awk "BEGIN {print 1/19}") $(awk "BEGIN {print 1/20}") $(awk "BEGIN {print 1/21}"))
ni=22500
intv=1
intt=50

le1=`expr $le - 1`
lc1=`expr $lc - 1`

for i in `seq 0 $le1`
do
for j in `seq 0 $lc1`
do
sbatch "<<ENTER THE WORKING DIRECTORY>>"thermodynamics ${answer} ${lattice} ${tempz} ${tempk} ${tempi} ${intname} ${jay} ${c[j]} ${radij} ${mrad} ${ls} ${side1} ${side2} 1 ${frac[i]} ${ni} ${intv} ${intt}
done
done
